import type { DeepSeekEndpointAuditRecord } from '../../types/deepseek-endpoint-audit.types.js'

const REGISTRY_CONFIRMED_ON = '2026-04-06'

export const DEEPSEEK_ENDPOINT_AUDIT_REGISTRY = {
  '/api/v0/chat/completion': {
    endpoint: '/api/v0/chat/completion',
    category: 'chat',
    confirmedOn: REGISTRY_CONFIRMED_ON,
    evidenceStatus: 'confirmed',
    sampleSources: ['real browser composer submit -> SSE generation stream'],
    fixturePaths: [
      'test/fixtures/deepseek-generation-stream/completion.real.fixture.json',
      'test/fixtures/deepseek-generation-stream/completion.stopped.real.fixture.json',
      'test/fixtures/deepseek-generation-stream/completion.search.real.fixture.json',
      'test/fixtures/deepseek-generation-stream/completion.search.rate-limit.real.fixture.json',
    ],
    consumedBy: {
      parser: true,
      adapter: true,
      exporter: false,
    },
    consumerSurfaces: [
      'deepSeekGenerationRuntime',
      'deepSeekGenerationStreamParser',
      'generationRunAccumulator',
      'openaiResponsesAdapter',
      'openaiChatCompletionsAdapter',
      'reply flows',
    ],
    unconfirmedFields: [
      'non-text fragment variants remain raw-only unless separately audited',
      'unhandled SSE events stay as raw observations',
    ],
    notes: [
      'primary generation endpoint for new-session and reply submit flows',
      'search-enabled real sample confirms DEEP_SEARCH stream can carry TOOL_SEARCH, TOOL_OPEN, and RESPONSE.references patches',
      'search rate-limit real sample confirms SSE hint.finish_reason=rate_limit_reached can co-occur with close.click_behavior=retry',
    ],
  },
  '/api/v0/chat/regenerate': {
    endpoint: '/api/v0/chat/regenerate',
    category: 'chat',
    confirmedOn: REGISTRY_CONFIRMED_ON,
    evidenceStatus: 'confirmed',
    sampleSources: ['real browser assistant message action -> regenerate'],
    fixturePaths: ['test/fixtures/deepseek-generation-stream/regenerate.real.fixture.json'],
    consumedBy: {
      parser: true,
      adapter: true,
      exporter: false,
    },
    consumerSurfaces: [
      'deepSeekGenerationRuntime',
      'deepSeekGenerationStreamParser',
      'generationRunAccumulator',
      'openai adapters',
      'regenerate flow',
    ],
    unconfirmedFields: ['non-default model_type semantics remain unmodeled'],
    notes: ['message-level regenerate path shares canonical generation runtime'],
  },
  '/api/v0/chat/continue': {
    endpoint: '/api/v0/chat/continue',
    category: 'chat',
    confirmedOn: REGISTRY_CONFIRMED_ON,
    evidenceStatus: 'confirmed',
    sampleSources: ['real browser inline Continue action -> SSE generation stream'],
    fixturePaths: ['test/fixtures/deepseek-generation-stream/continue.real.fixture.json'],
    consumedBy: {
      parser: true,
      adapter: true,
      exporter: false,
    },
    consumerSurfaces: [
      'deepSeekGenerationRuntime',
      'deepSeekGenerationStreamParser',
      'generationRunAccumulator',
      'openai adapters',
      'continue flow',
    ],
    unconfirmedFields: ['cross-branch continue materialization beyond audited sample remains guarded'],
    notes: ['explicit continue stays separate from restore-time auto-resume evidence'],
  },
  '/api/v0/chat/edit_message': {
    endpoint: '/api/v0/chat/edit_message',
    category: 'chat',
    confirmedOn: REGISTRY_CONFIRMED_ON,
    evidenceStatus: 'confirmed',
    sampleSources: ['real browser edit action with prefilled composer -> SSE generation stream'],
    fixturePaths: ['test/fixtures/deepseek-generation-stream/edit_message.real.fixture.json'],
    consumedBy: {
      parser: true,
      adapter: true,
      exporter: false,
    },
    consumerSurfaces: [
      'deepSeekGenerationRuntime',
      'deepSeekGenerationStreamParser',
      'generationRunAccumulator',
      'openai adapters',
      'edit-message flow',
    ],
    unconfirmedFields: ['edit follow-up variants beyond current inline path remain unmodeled'],
    notes: ['edit-mode composer semantics are handled separately from normal reply input clearing'],
  },
  '/api/v0/chat/history_messages': {
    endpoint: '/api/v0/chat/history_messages',
    category: 'chat',
    confirmedOn: REGISTRY_CONFIRMED_ON,
    evidenceStatus: 'confirmed',
    sampleSources: [
      'real browser session recovery',
      'real browser mutation recovery',
      'real browser WIP / active-view observations',
      'real browser first-message recovery with attached file',
      'real browser reply recovery with attached file and cache_control=MERGE',
    ],
    fixturePaths: [
      'test/fixtures/deepseek-history-messages/history-messages.real.fixture.json',
      'test/fixtures/deepseek-history-messages/history-messages.search.real.fixture.json',
      'test/fixtures/deepseek-history-messages/history-messages.attachments.first-message.real.fixture.json',
      'test/fixtures/deepseek-history-messages/history-messages.attachments.reply.real.fixture.json',
      'test/fixtures/deepseek-history-messages/history-messages.edit-message.real.fixture.json',
      'test/fixtures/deepseek-history-messages/history-messages.regenerate.empty-merge.real.fixture.json',
      'test/fixtures/deepseek-history-messages/history-messages.continue.in-place.real.observation.json',
      'test/fixtures/deepseek-history-messages/history-messages.regenerate.active-view.real.observation.json',
      'test/fixtures/deepseek-stream-control/history-messages.wip.real.fixture.json',
    ],
    consumedBy: {
      parser: false,
      adapter: false,
      exporter: true,
    },
    consumerSurfaces: [
      'deepSeekHistoryMessages',
      'transcript recovery',
      'continue preflight',
      'branch materialization',
      'session export snapshot',
    ],
    unconfirmedFields: [
      'MERGE / active-view-only semantics remain guarded by provenance flags',
      'cache_control variants remain observation-only outside audited paths',
    ],
    notes: [
      'authoritative transcript recovery source for stable assistant text and export provenance',
      'search-enabled real sample confirms assistant RESPONSE.references can point to TOOL_OPEN / TOOL_SEARCH fragments instead of top-level citations arrays',
      'real attachment-bearing samples confirm chat_messages[].files is the transcript-side attachment source',
      'attachment-bearing MERGE recovery can omit richer local preview metadata, so stored-session/export keep field-level overlays instead of last-write-wins replacement',
    ],
  },
  '/api/v0/chat/stop_stream': {
    endpoint: '/api/v0/chat/stop_stream',
    category: 'chat',
    confirmedOn: REGISTRY_CONFIRMED_ON,
    evidenceStatus: 'confirmed',
    sampleSources: ['real browser stop button during streaming generation'],
    fixturePaths: ['test/fixtures/deepseek-stream-control/stop_stream.real.fixture.json'],
    consumedBy: {
      parser: false,
      adapter: false,
      exporter: false,
    },
    consumerSurfaces: [
      'stream control observer',
      'generation settlement',
      'continue-target helper',
      'continue preflight',
    ],
    unconfirmedFields: [],
    notes: ['control-plane stop acknowledgement is modeled separately from SSE generation content'],
  },
  '/api/v0/chat/resume_stream': {
    endpoint: '/api/v0/chat/resume_stream',
    category: 'chat',
    confirmedOn: REGISTRY_CONFIRMED_ON,
    evidenceStatus: 'confirmed',
    sampleSources: ['real browser resumed stream after stopped generation'],
    fixturePaths: ['test/fixtures/deepseek-generation-stream/resume_stream.real.fixture.json'],
    consumedBy: {
      parser: true,
      adapter: true,
      exporter: false,
    },
    consumerSurfaces: [
      'deepSeekGenerationRuntime',
      'deepSeekGenerationStreamParser',
      'stream control observer',
      'continue preflight',
      'openai adapters',
    ],
    unconfirmedFields: ['resume-specific metadata beyond observed canonical run context remains raw-only'],
    notes: ['resume_stream is treated as a generation-bearing endpoint in canonical runtime'],
  },
  '/api/v0/chat/message_feedback': {
    endpoint: '/api/v0/chat/message_feedback',
    category: 'chat',
    confirmedOn: REGISTRY_CONFIRMED_ON,
    evidenceStatus: 'confirmed',
    sampleSources: ['real browser assistant Like action -> POST message_feedback'],
    fixturePaths: ['test/fixtures/deepseek-chat-auxiliary/message_feedback.real.fixture.json'],
    consumedBy: {
      parser: false,
      adapter: false,
      exporter: false,
    },
    consumerSurfaces: ['audit-only'],
    unconfirmedFields: [
      'feedback_type variants beyond GOOD are not yet confirmed',
      'dislike follow-up UI payloads are not yet confirmed',
    ],
    notes: ['current real sample covers assistant Like without extra modal'],
  },
  '/api/v0/chat/create_pow_challenge': {
    endpoint: '/api/v0/chat/create_pow_challenge',
    category: 'chat',
    confirmedOn: REGISTRY_CONFIRMED_ON,
    evidenceStatus: 'confirmed',
    sampleSources: ['real browser composer submit preflight before /api/v0/chat/completion'],
    fixturePaths: ['test/fixtures/deepseek-chat-auxiliary/create_pow_challenge.real.fixture.json'],
    consumedBy: {
      parser: false,
      adapter: false,
      exporter: false,
    },
    consumerSurfaces: ['audit-only'],
    unconfirmedFields: [
      'challenge solving semantics are intentionally unmodeled',
      'challenge, salt, and signature values are redacted and not treated as product contract',
    ],
    notes: ['only request/response boundary and target_path are recorded; no PWO reverse engineering'],
  },
  '/api/v0/chat_session/create': {
    endpoint: '/api/v0/chat_session/create',
    category: 'chat-session',
    confirmedOn: REGISTRY_CONFIRMED_ON,
    evidenceStatus: 'confirmed',
    sampleSources: ['real browser authenticated home bootstrap'],
    fixturePaths: ['test/fixtures/deepseek-chat-session/create.real.fixture.json'],
    consumedBy: {
      parser: false,
      adapter: false,
      exporter: false,
    },
    consumerSurfaces: ['deepSeekSessionTransition', 'stored session metadata'],
    unconfirmedFields: ['ttl_seconds is observed but not consumed'],
    notes: ['sessionCreate is auxiliary evidence only and never overrides final session route authority'],
  },
  '/api/v0/chat_session/delete': {
    endpoint: '/api/v0/chat_session/delete',
    category: 'chat-session',
    confirmedOn: REGISTRY_CONFIRMED_ON,
    evidenceStatus: 'confirmed',
    sampleSources: ['real browser sidebar overflow -> Delete -> confirm modal'],
    fixturePaths: ['test/fixtures/deepseek-chat-session/delete.real.fixture.json'],
    consumedBy: {
      parser: false,
      adapter: false,
      exporter: false,
    },
    consumerSurfaces: ['delete-session flow'],
    unconfirmedFields: [],
    notes: ['single-session destructive flow is productized with explicit CLI guardrails'],
  },
  '/api/v0/chat_session/delete_all': {
    endpoint: '/api/v0/chat_session/delete_all',
    category: 'chat-session',
    confirmedOn: null,
    evidenceStatus: 'pending_internal_audit',
    sampleSources: ['real browser account menu -> Settings -> Data -> Delete all chats UI observation'],
    fixturePaths: [
      'test/fixtures/deepseek-chat-session/delete_all.pending.real.observation.json',
    ],
    consumedBy: {
      parser: false,
      adapter: false,
      exporter: false,
    },
    consumerSurfaces: ['catalog-only'],
    unconfirmedFields: ['full request / response payload remains intentionally uncaptured pending internal audit'],
    notes: ['high-destruction action remains non-productized and blocked from CLI / interactive / RPC exposure'],
  },
  '/api/v0/chat_session/fetch_page': {
    endpoint: '/api/v0/chat_session/fetch_page',
    category: 'chat-session',
    confirmedOn: REGISTRY_CONFIRMED_ON,
    evidenceStatus: 'confirmed',
    sampleSources: ['real browser authenticated home bootstrap'],
    fixturePaths: ['test/fixtures/deepseek-chat-session/fetch_page.real.fixture.json'],
    consumedBy: {
      parser: false,
      adapter: false,
      exporter: false,
    },
    consumerSurfaces: ['audit-only'],
    unconfirmedFields: ['fields beyond id/title/title_type/pinned/updated_at/has_more stay raw-only'],
    notes: ['current implementation intentionally does not consume fetch_page for session restore'],
  },
  '/api/v0/chat_session/update_pinned': {
    endpoint: '/api/v0/chat_session/update_pinned',
    category: 'chat-session',
    confirmedOn: REGISTRY_CONFIRMED_ON,
    evidenceStatus: 'confirmed',
    sampleSources: ['real browser sidebar overflow -> Pin'],
    fixturePaths: ['test/fixtures/deepseek-chat-session/update_pinned.real.fixture.json'],
    consumedBy: {
      parser: false,
      adapter: false,
      exporter: false,
    },
    consumerSurfaces: ['audit-only'],
    unconfirmedFields: [],
    notes: ['endpoint is audited but not yet productized as a user-facing command'],
  },
  '/api/v0/chat_session/update_title': {
    endpoint: '/api/v0/chat_session/update_title',
    category: 'chat-session',
    confirmedOn: REGISTRY_CONFIRMED_ON,
    evidenceStatus: 'confirmed',
    sampleSources: ['real browser sidebar overflow -> Rename -> inline input -> Enter'],
    fixturePaths: ['test/fixtures/deepseek-chat-session/update_title.real.fixture.json'],
    consumedBy: {
      parser: false,
      adapter: false,
      exporter: false,
    },
    consumerSurfaces: ['audit-only'],
    unconfirmedFields: [],
    notes: ['endpoint is audited but not yet productized as a user-facing command'],
  },
  '/api/v0/file/upload_file': {
    endpoint: '/api/v0/file/upload_file',
    category: 'file',
    confirmedOn: REGISTRY_CONFIRMED_ON,
    evidenceStatus: 'confirmed',
    sampleSources: ['real browser composer file upload'],
    fixturePaths: [
      'test/fixtures/deepseek-file-uploads/upload_file.success.real.fixture.json',
      'test/fixtures/deepseek-file-uploads/upload_file.parsing.real.fixture.json',
      'test/fixtures/deepseek-file-uploads/upload_file.success_terminal.real.fixture.json',
      'test/fixtures/deepseek-file-uploads/upload_file.unsupported_type.real.fixture.json',
    ],
    consumedBy: {
      parser: false,
      adapter: false,
      exporter: false,
    },
    consumerSurfaces: ['deepSeekFileUploadRuntime'],
    unconfirmedFields: ['server-side scanning or delayed rejection metadata remains raw-only'],
    notes: [
      'real samples now cover PENDING, PARSING, terminal SUCCESS, and unsupported-type rejection',
    ],
  },
  '/api/v0/file/preview': {
    endpoint: '/api/v0/file/preview',
    category: 'file',
    confirmedOn: REGISTRY_CONFIRMED_ON,
    evidenceStatus: 'confirmed',
    sampleSources: ['real browser file attachment preview before send'],
    fixturePaths: [
      'test/fixtures/deepseek-file-uploads/preview.unsent.success.real.fixture.json',
      'test/fixtures/deepseek-file-uploads/preview.unsent.missing_token.real.fixture.json',
    ],
    consumedBy: {
      parser: false,
      adapter: false,
      exporter: false,
    },
    consumerSurfaces: ['deepSeekFileUploadRuntime'],
    unconfirmedFields: ['plain direct browser fetch may return Missing Token outside app-authenticated request paths'],
    notes: ['preview is audited as pre-send attachment path, not as a general document renderer'],
  },
  '/api/v0/file/fetch_files': {
    endpoint: '/api/v0/file/fetch_files',
    category: 'file',
    confirmedOn: REGISTRY_CONFIRMED_ON,
    evidenceStatus: 'confirmed',
    sampleSources: ['real browser attachment settle polling after upload'],
    fixturePaths: [
      'test/fixtures/deepseek-file-uploads/fetch_files.success.real.fixture.json',
      'test/fixtures/deepseek-file-uploads/fetch_files.invalid_token.real.fixture.json',
    ],
    consumedBy: {
      parser: false,
      adapter: false,
      exporter: true,
    },
    consumerSurfaces: ['deepSeekFileUploadRuntime', 'stored attachment metadata', 'session export'],
    unconfirmedFields: ['late browser settle timing beyond current samples remains environment-dependent'],
    notes: ['attachment metadata captured here can flow into persisted session/export output'],
  },
} as const satisfies Record<string, DeepSeekEndpointAuditRecord>

export function describeDeepSeekEndpointAuditRegistry(): DeepSeekEndpointAuditRecord[] {
  return Object.values(DEEPSEEK_ENDPOINT_AUDIT_REGISTRY).map(record => ({
    ...record,
    sampleSources: [...record.sampleSources],
    fixturePaths: [...record.fixturePaths],
    consumedBy: { ...record.consumedBy },
    consumerSurfaces: [...record.consumerSurfaces],
    unconfirmedFields: [...record.unconfirmedFields],
    notes: [...record.notes],
  }))
}

export function getDeepSeekEndpointAuditRecord(endpoint: string): DeepSeekEndpointAuditRecord | null {
  const record = DEEPSEEK_ENDPOINT_AUDIT_REGISTRY[endpoint as keyof typeof DEEPSEEK_ENDPOINT_AUDIT_REGISTRY]
  if (!record) {
    return null
  }

  return {
    ...record,
    sampleSources: [...record.sampleSources],
    fixturePaths: [...record.fixturePaths],
    consumedBy: { ...record.consumedBy },
    consumerSurfaces: [...record.consumerSurfaces],
    unconfirmedFields: [...record.unconfirmedFields],
    notes: [...record.notes],
  }
}
